image: maven:3.8.7-openjdk-18-slim

stages:
  - test

test:
  stage: test
  script:
    - mvn clean test
  tags:
  artifacts:
    when: always
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
