image: rvancea/maven-chrome-jdk15:latest
  

build:
  stage: build
  script:
    - mvn compile
  tags:
    - cluster
    - kubernetes
    
test:
  stage: test
  script:
    -mvn clean test
  tags:
    - cluster
    - kubernetes