image: markhobson/maven-chrome:jdk-15
variables:
  CBT_USERNAME: earl@swarmio.media
  CBT_AUTHKEY: u0e572444a5c9073

build:
  stage: build
  script:
    - mvn compile
  tags:
    - cluster
    - kubernetes
  artifacts:
    when: always
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/failsafe-reports/TEST-*.xml

test:
  stage: test
  script:
    - mvn clean test
  tags:
    - cluster
    - kubernetes
  artifacts:
    when: always
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/failsafe-reports/TEST-*.xml