image: maven:3.3.9-jdk-8

before_script:
  - |
    until docker ps; do sleep 3; done
    cd $CI_PROJECT_DIR
    # cd /builds/earl/jmeter-tests
    echo 'export LT_USERNAME=earlswarmio' >> ~/.bashrc
    echo 'export LT_ACCESS_KEY=4hear2v5UZ2nAJ10bsBzjPrxYJgqyEa8T1oa7dvfCL2ZFJtdLG' >> ~/.bashrc

stages:
  - build
  - test

build:
  stage: build
  script:
    - mvn compile
  tags:
  artifacts:
    when: always
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml

test:
  stage: test
  script:
    - mvn clean test
  tags:
  artifacts:
    when: always
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
