image: markhobson/maven-chrome:jdk-15

build:
  stage: build
  script:
    - mvn compile
  tags:
    - cluster
    - kubernetes
  artifacts:
    when: always
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/failsafe-reports/TEST-*.xml

test:
  stage: test
  script:
    - mvn clean test
  tags:
    - cluster
    - kubernetes
  artifacts:
    when: always
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/failsafe-reports/TEST-*.xml
functional_tests:
  stage: functional
  script:
    - echotesting $ARCHITECTURE $TARGET $VERSION
  parallel:
    - ENVIRONMENT: [windows, mac, ios, android]
      BROWSER: [chrome, safari, ie]