image: markhobson/maven-chrome:jdk-15
  

build:
  stage: build
  script:
    - mvn compile
  tags:
    - cluster
    - kubernetes
    
test:
  stage: test
  script:
    - mvn clean test
  tags:
    - cluster
    - kubernetes