variables:
  DOCKER_REGISTRY: registry.swarmio.gg/earl
  BUILDER_IMAGE: $DOCKER_REGISTRY/jmeter-tests:builder

stages:
  - pre-build
  - test

build-builder:
  stage: pre-build
  script:
    - docker build --no-cache --pull -t $BUILDER_IMAGE . -f builder.Dockerfile
    - docker push $BUILDER_IMAGE
  when: manual

test:
  image: registry.swarmio.gg/earl/jmeter-tests:builder #use a custom image that we've built from the pre-step
  stage: test
  script:
    - mvn clean test
  artifacts:
    when: always
    # add an artifact for dumps
    paths:
      - exports/*
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/failsafe-reports/TEST-*.xml
